import json
import os
import re
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from sys import argv, exit, stderr
from typing import TypedDict

import yaml
from jinja2 import Environment, FileSystemLoader

from .config import Config, HERE, testrun_id
from .errors import ConfigError
from .log import info, success, warning

METRICS_FILE = HERE / "files" / "metrics.yaml"
PROMPT_FILE = HERE / "files" / "report-prompt.txt"

MONTHS = [
    "janeiro", "fevereiro", "março", "abril", "maio", "junho",
    "julho", "agosto", "setembro", "outubro", "novembro", "dezembro",
]



COLUMN_TYPES: dict[str, type] = {"str": str, "int": int, "float": float}

UNIT_LABELS: dict[str, tuple[str, str]] = {
    "h": ("hora", "horas"),
    "m": ("minuto", "minutos"),
    "s": ("segundo", "segundos"),
}

# Testrun IDs are generated by the justfile as `{prefix}--{env}--{lt|sm}--{YYMMDDHHmm}`.
# Validate before interpolating into SQL to prevent injection via malformed IDs.
TESTRUN_PATTERN = re.compile(r"^[a-z0-9][a-z0-9\-]+$")

Row = dict[str, str | int | float]


class QueryDefRaw(TypedDict):
    sql: str
    group_by: str | None
    columns: dict[str, str]


class MetricsFileRaw(TypedDict):
    queries: dict[str, QueryDefRaw]


@dataclass
class QueryDef:
    name: str
    sql: str
    group_by: str | None
    columns: dict[str, type]


@dataclass
class ScenarioMetrics:
    scenario: str
    total_reqs: int
    avg_ms: float
    max_ms: float
    pct_25ms: float
    pct_100ms: float
    pct_500ms: float
    pct_1s: float

    @property
    def label(self) -> str:
        return self.scenario


@dataclass
class WindowMetrics:
    started_at: str = "—"
    ended_at: str = "—"
    elapsed_min: str | int | float = "—"


def to_window_metrics(row: Row) -> WindowMetrics:
    return WindowMetrics(
        started_at=str(row.get("started_at", "—")),
        ended_at=str(row.get("ended_at", "—")),
        elapsed_min=row.get("elapsed_min", "—"),
    )


def duration_label(raw: str) -> str:
    rest = raw.strip()
    segments: list[str] = []
    for unit in ("h", "m", "s"):
        before, found, after = rest.partition(unit)
        if not found:
            continue
        if not before.isdigit():
            return raw
        n = int(before)
        singular, plural = UNIT_LABELS[unit]
        segments.append(f"{n} {singular if n == 1 else plural}")
        rest = after
    if not segments or rest:
        return raw
    return ", ".join(segments)


def load_queries(path: Path) -> dict[str, QueryDef]:
    raw: MetricsFileRaw = yaml.safe_load(path.read_text())
    if "queries" not in raw:
        raise ValueError(f"'{path}' is missing top-level 'queries' key")
    queries: dict[str, QueryDef] = {}
    for name, entry in raw["queries"].items():
        for key in ("sql", "columns"):
            if key not in entry:
                raise ValueError(f"Query '{name}' is missing required key '{key}'")
        if "{testrun}" not in entry["sql"]:
            raise ValueError(f"Query '{name}' SQL is missing the '{{testrun}}' placeholder")
        unknown = [t for t in entry["columns"].values() if t not in COLUMN_TYPES]
        if unknown:
            raise ValueError(f"Query '{name}' has unknown column types: {', '.join(unknown)}")
        columns = {col: COLUMN_TYPES[typ] for col, typ in entry["columns"].items()}
        queries[name] = QueryDef(
            name=name,
            sql=entry["sql"].strip(),
            group_by=entry.get("group_by"),
            columns=columns,
        )
    return queries


def coerce_row(row: Row, columns: dict[str, type]) -> Row:
    return {k: columns[k](v) if k in columns else v for k, v in row.items()}


def run_query(cfg: Config, qdef: QueryDef, testrun: str) -> list[Row]:
    if not TESTRUN_PATTERN.match(testrun):
        raise ConfigError(f"Invalid testrun ID '{testrun}' — must match {TESTRUN_PATTERN.pattern}")
    sql = qdef.sql.format(testrun=testrun)
    result = subprocess.run(
        [
            "kubectl", f"--context={cfg.context}",
            "-n", cfg.clickhouse_namespace,
            "exec", cfg.clickhouse_pod,
            "--", "clickhouse-client", "--query", sql,
        ],
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        warning(result.stderr.strip())
        return []
    rows: list[Row] = [json.loads(line) for line in result.stdout.strip().splitlines() if line]
    return [coerce_row(row, qdef.columns) for row in rows]


def index_by(rows: list[Row], key: str | None) -> dict[str, Row]:
    if not key:
        return {}
    return {str(row[key]): row for row in rows if row.get(key)}


def fetch_metrics(
    cfg: Config,
    queries: dict[str, QueryDef],
    scenarios: list[str],
) -> tuple[list[ScenarioMetrics], WindowMetrics]:
    totals = index_by(run_query(cfg, queries["totals"], cfg.testrun), queries["totals"].group_by)
    distributions = index_by(
        run_query(cfg, queries["distribution"], cfg.testrun),
        queries["distribution"].group_by,
    )
    windows = run_query(cfg, queries["window"], cfg.testrun)
    window = to_window_metrics(windows[0]) if windows else WindowMetrics()

    metrics: list[ScenarioMetrics] = []
    for s in scenarios:
        t = totals.get(s)
        if t is None:
            warning(f"No totals found for scenario '{s}' in testrun '{cfg.testrun}' — skipping")
            continue
        metrics.append(
            ScenarioMetrics(
                scenario=s,
                total_reqs=int(t.get("total_reqs", 0)),
                avg_ms=float(t.get("avg_ms", 0.0)),
                max_ms=float(t.get("max_ms", 0.0)),
                pct_25ms=float(distributions.get(s, {}).get("pct_25ms", 0.0)),
                pct_100ms=float(distributions.get(s, {}).get("pct_100ms", 0.0)),
                pct_500ms=float(distributions.get(s, {}).get("pct_500ms", 0.0)),
                pct_1s=float(distributions.get(s, {}).get("pct_1s", 0.0)),
            )
        )
    return metrics, window


def interpret(cfg: Config, metrics: list[ScenarioMetrics], window: WindowMetrics) -> str | None:
    lines = [
        f"Identificador: {cfg.testrun}",
        f"Ambiente: {cfg.prefix} / {cfg.env}",
        f"Início: {window.started_at} UTC",
        f"Término: {window.ended_at} UTC",
        f"Duração: {window.elapsed_min} minutos",
        f"Meta de RPS: {cfg.target_rps} req/s",
        f"Total de requisições: {sum(m.total_reqs for m in metrics):,}",
        "",
        "Resultados por serviço:",
        *[
            f"  {m.label}: {m.total_reqs:,} reqs, avg {m.avg_ms:.0f}ms, max {m.max_ms:.0f}ms, "
            f"<25ms={m.pct_25ms}%, <100ms={m.pct_100ms}%, <500ms={m.pct_500ms}%, <1s={m.pct_1s}%"
            for m in metrics
        ],
    ]
    prompt = PROMPT_FILE.read_text().format(data="\n".join(lines))
    result = subprocess.run(["opencode", "run", prompt], text=True, capture_output=True)
    if result.returncode != 0:
        warning("opencode failed — skipping interpretation")
        return None
    return result.stdout.strip() or None


def render_section(
    cfg: Config,
    metrics: list[ScenarioMetrics],
    window: WindowMetrics,
    interpretation: str | None,
    jinja_env: Environment,
) -> str:
    now = datetime.now(timezone.utc)
    date_str = f"{now.day} de {MONTHS[now.month - 1]} de {now.year}"
    return jinja_env.get_template("report.md.j2").render(
        date=date_str,
        testrun=cfg.testrun,
        script_file=cfg.script_file,
        env_label=f"{cfg.prefix} / {cfg.env}",
        started_at=window.started_at,
        ended_at=window.ended_at,
        elapsed_min=window.elapsed_min,
        target_rps=cfg.target_rps,
        sustained_duration_label=duration_label(cfg.sustained_duration),
        metrics=metrics,
        total_reqs=sum(m.total_reqs for m in metrics),
        interpretation=interpretation,
    )


def script_to_scenario(script: str) -> str:
    suffix = script.split("--", 1)[1] if "--" in script else script
    return suffix.replace("-", "_")


def run_report(base_id: str, configs: list[Config], skip_interpretation: bool = False) -> None:
    if not configs:
        warning("No configs provided — skipping")
        return

    queries = load_queries(METRICS_FILE)
    jinja_env = Environment(
        loader=FileSystemLoader(str(HERE / "files")),
        keep_trailing_newline=True,
    )
    sections: list[str] = []

    for cfg in configs:
        info(f"Fetching metrics for '{cfg.testrun}' via {cfg.context}...")
        scenarios = [script_to_scenario(cfg.script_file)]
        metrics, window = fetch_metrics(cfg, queries, scenarios)

        if not metrics:
            warning(f"No metrics found for '{cfg.testrun}' — skipping")
            continue

        interpretation: str | None = None
        if not skip_interpretation:
            info("Generating interpretation...")
            interpretation = interpret(cfg, metrics, window)

        sections.append(render_section(cfg, metrics, window, interpretation, jinja_env))

    if not sections:
        warning("No sections generated — skipping report")
        return

    first = configs[0]
    now = datetime.now(timezone.utc)
    date_str = f"{now.day} de {MONTHS[now.month - 1]} de {now.year}"

    header = jinja_env.get_template("combined.md.j2").render(
        date=date_str,
        prefix=first.prefix,
        base_id=base_id,
        env_label=f"{first.prefix} / {first.env}",
    )

    combined = header + "\n\n---\n\n".join(s.rstrip("\n") for s in sections) + "\n"

    first.reports_dir.mkdir(parents=True, exist_ok=True)
    output = first.reports_dir / f"{base_id}.md"
    output.write_text(combined)

    success(f"Report written to '{output}'")


def main() -> None:
    args = argv[1:]
    if len(args) < 2:
        print("Usage: python3 -m scripts.report <base-id> <script> [<script> ...]", file=stderr)
        exit(1)

    base_id = args[0]
    scripts = args[1:]
    no_interpretation = os.environ.get("NO_INTERPRETATION", "false").lower() == "true"

    configs = [Config(testrun=testrun_id(base_id, s), script_file=s, smoke=False) for s in scripts]
    run_report(base_id, configs, skip_interpretation=no_interpretation)


if __name__ == "__main__":
    main()
